INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'aa', 'aa', 'aa', 'aa@aa');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'bb', 'bb', 'bb', 'bb@bb');

INSERT INTO QUESTION(WRITER_ID, TITLE, CONTENTS, CREATED_AT) VALUES (1, 'test 1', ' test 1', CURRENT_TIMESTAMP());
INSERT INTO QUESTION(WRITER_ID, TITLE, CONTENTS, CREATED_AT) VALUES (2, 'test 2', ' test 2', CURRENT_TIMESTAMP());