INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('aa', 'aa', 'aa', 'aa@aa');
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('bb', 'bb', 'bb', 'bb@bb');

INSERT INTO QUESTION(WRITER, TITLE, CONTENTS) VALUES ('aa', 'test 1', ' test 1');