INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATED_AT) VALUES (1, 'aa', 'aa', 'aa', 'aa@aa',  CURRENT_TIMESTAMP());
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATED_AT) VALUES (2, 'bb', 'bb', 'bb', 'bb@bb',  CURRENT_TIMESTAMP());

INSERT INTO QUESTION(WRITER_ID, TITLE, CONTENTS, count_of_answer) VALUES (1, 'test 1', ' test 1', 0);
INSERT INTO QUESTION(WRITER_ID, TITLE, CONTENTS, count_of_answer) VALUES (2, 'test 2', ' test 2', 0);