INSERT INTO category(ID, NAME, REG_DATE) VALUES (1, 'spring', CURRENT_TIMESTAMP());
INSERT INTO category(ID, NAME, REG_DATE) VALUES (2, 'java', CURRENT_TIMESTAMP());
INSERT INTO category(ID, NAME, REG_DATE) VALUES (3, 'python', CURRENT_TIMESTAMP());

INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (1, 'test1', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 1);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (2, 'test2', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 2);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (3, 'test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);

INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (4, 'test1', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 1);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (5, 'test2', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 2);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (6, 'test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);

INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (7, 'test1', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 1);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (8, 'test2', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 2);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (9, 'test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);

INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (10, 'test1', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 1);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (11, 'test2', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 2);
INSERT INTO post(ID, TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES (12, 'test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);

INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);
INSERT INTO post(TITLE, CODE, CONTENT, STATUS, REG_DATE, CATEGORY_ID) VALUES ('test3', 'test post', '지금은 테스트', 'Y', CURRENT_TIMESTAMP(), 3);

